
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'project_dbt_etl'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'snowflake_connection'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  project_dbt_etl:
      # Applies to all files under models/example/
      stg:
          materialized: view

seeds:
  project_dbt_etl:
    datachallenge:
      +column_types:
        quote_date: varchar(25)
        lane: varchar(100)
        book_date: varchar(25)
        source_date: varchar(25)
        pickup_date: varchar(25)
        delivery_date: varchar(25)
        equipment_type: varchar(100)
        sourcing_channel: varchar(100)
        carrier_name: varchar(100)
        shipper_name: varchar(100)
        pickup_appointment_time: varchar(25)
        delivery_appointment_time: varchar(25)
        
dispatch:
  - macro_namespace: dbt_utils
    search_order:
      - dbt_utils                  # always include dbt_utils as the last place to search